### ISSUE TITLE
Documentation is out of sync

### ISSUE THREAD

**Issue by SamVanhoutte** [solidify/github-action-update-azapim#272]
Hello,

I am really interested in this action, as it seems to promise exactly what I need...  Importing a swagger into Azure APIM.
However, wanted to raise that the documentation is out of sync.

The docs (and also on the Github marketplace) are having this snippet:

```yaml
- name: Update Azure API Management
  uses: solidify/github-action-update-azapim@master
  with:
    swaggerPath: 'URL/path to Swagger'
    apiManager: ${{ secrets.API_MANAGER_URL }}
    creds: ${{ secrets.AZURE_CREDENTIALS }}
```

However, it seems I had to change it to the following

- name: Update Azure API Management
  uses: solidify/github-action-update-azapim@master
  with:
    swaggerUrl: 'URL/path to Swagger'
    apiManagementEndpointUrl: ${{ secrets.API_MANAGER_URL }}
    creds: ${{ secrets.AZURE_CREDENTIALS }}
```
